// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuNX2DgBxdNzhj2d4ij6uyyqpXec3TMQ',
    appId: '1:989742825315:web:87d554d851ed89a717dd56',
    messagingSenderId: '989742825315',
    projectId: 'quiznetic-30734',
    authDomain: 'quiznetic-30734.firebaseapp.com',
    storageBucket: 'quiznetic-30734.firebasestorage.app',
    measurementId: 'G-W0CM8C9NE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf0dulhlgoNZRXV-iLIEHhM9a6NNL8Sjc',
    appId: '1:989742825315:android:f8141c45d184257217dd56',
    messagingSenderId: '989742825315',
    projectId: 'quiznetic-30734',
    storageBucket: 'quiznetic-30734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFleaftelJvJ58_yAPU6aK8yHX_xilSX8',
    appId: '1:989742825315:ios:807d44c9c7fbd09b17dd56',
    messagingSenderId: '989742825315',
    projectId: 'quiznetic-30734',
    storageBucket: 'quiznetic-30734.firebasestorage.app',
    iosBundleId: 'com.example.quizneticFlutter',
  );
}
